# Generated by Django 3.2.7 on 2021-10-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fathers_and_sons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='gender',
            field=models.CharField(default='man', max_length=10),
        ),
        migrations.AddField(
            model_name='record',
            name='imt',
            field=models.FloatField(default='0.0'),
        ),
        migrations.AddField(
            model_name='record',
            name='result',
            field=models.CharField(default='No', max_length=30),
        ),
        migrations.AlterField(
            model_name='record',
            name='height',
            field=models.FloatField(),
        ),
    ]
